{% set name = "httpx-aiohttp" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/httpx_aiohttp-{{ version }}.tar.gz
  sha256: 0d49841c836aaa0824b603b2e28bcaa0e20f808b31d1ef8930be107cdbceeffd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.10.0,<4
    - httpx >=0.27.0

test:
  imports:
    - httpx_aiohttp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Aiohttp transport for HTTPX
  home: https://github.com/karpetrosyan/httpx-aiohttp
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
